### ISSUE TITLE
Can't find matplotlib

### ISSUE THREAD

**Issue by harshcurious** [jmerle/zeal-user-contrib#14]
I checked and it exists in the [Dash website](https://kapeli.com/dash#docsets). Can you help me understand why it's not showing up in my search?

PS: Thanks for the awesome script!

Sorry, My bad. Misunderstood the meaning of user contrib. Silly me 🙁

**Comment by jmerle** [comment]
The matplotlib docset is part of Dash's core docsets, zeal-user-contrib is for adding Dash's [user contributed docsets](https://github.com/Kapeli/Dash-User-Contributions) to Zeal (using feeds from [zealusercontributions.vercel.app](https://zealusercontributions.vercel.app/)). Dash's core docsets are already available through Zeal's Docsets window:  
![](https://user-images.githubusercontent.com/14951909/144717658-e17a3417-a1ca-45b7-a58b-1882858d3ec0.png)

**Comment by harshcurious** [comment]
Thanks for the reply and the repo!
